### ISSUE TITLE
Video compressing

### ISSUE THREAD

**Issue by stardevrk** [cloudinary/cloudinary-ios-sample-app#3]
I have just tested this sample iOS app.
I could see video was compressing before uploaded. Can I avoid this compressing?
We should upload specific video. We should analyze meta data in video. So if video is compressed, we can not analyze video. 
Please let me know your solution.
Thanks.

**Comment by shirlymanor** [comment]
@stardevrk can you please share more information on how do you see that it compressed? Can you please share your cloud name, upload preset and the video public_id? If privacy is an issue please feel free to open a ticket at support@cloudinary.com

**Comment by stardevrk** [comment]
@shirlymanor 
Simply when I use your sample app, after I choose one video and click 'Choose' button, I can see 'Compressing' progress bar.
Is it compressing of video?

**Comment by shirlymanor** [comment]
The progress bar is to show the status of the upload.
The video is upload as is. You can add transformations as incoming or eagerly. Our best practice is to upload as-is and add the  [video transformations eagerly](http://cloudinary.com/documentation/upload_videos#eager_video_transformations). 

Eager transformations can be set upon upload or by updating your current resources using the [explicit](http://cloudinary.com/documentation/image_upload_api_reference#explicit) API.

**Comment by stardevrk** [comment]
@shirlymanor 
Thank you for your quick reply.
After I tap 'Choose' button in your sample app's file picker, I could see 'Compressing' progress bar in same screen. After that file picker was disappeared and I could see one file in the main page of sample app, and I could see another progress bar to be uploaded.
Now I am not sure what it means 'Compressing' progress bar. I guess it is compressing the video before uploading. 
Please le me know about 'Compressing'.
Thanks.

**Comment by shirlymanor** [comment]
@stardevrk Can you please compare the uploaded video (in Cloudinary) vs your original video? Please let me know if they are different.

**Comment by stardevrk** [comment]
@shirlymanor 
I have just check original video and uploaded video using this sample app. 
Original Video: 91.4MB
UploadedVideo: 87.17MB

It means it is compressed. If you have any solution to avoid this compression, please let me know.

Thanks.

**Comment by shirlymanor** [comment]
It is the same - it's MB vs MIB:

<img width="1069" alt="Screen Shot 2019-12-11 at 3 02 13 PM" src="https://user-images.githubusercontent.com/604899/70668047-5135bd00-1c27-11ea-931f-ba9a5c39e39d.png">

**Comment by stardevrk** [comment]
I have just downloaded that video to my windows machine.
But windows shows 87.2MB. Is this 87.2MiB?

**Comment by shirlymanor** [comment]
@stardevrk can you share the URL for the video? As a side note, if you would optimize with cloudinary (e.g., use f_auto,q_auto`) you might be able to save around 30% of the original size.

**Comment by stardevrk** [comment]
@shirlymanor 
https://res.cloudinary.com/deo52frj8/video/upload/v1576099553/etk2ni0hzdzzg540pdbb.mov

This is the video link. I don't want to lose any information from video. So I want to avoid any compression or transformation.

**Comment by shirlymanor** [comment]
@stardevrk I tried:
`curl -I https://res.cloudinary.com/deo52frj8/video/upload/v1576099553/etk2ni0hzdzzg540pdbb.mov`

And the response was `content-length: 91401044` I believe you will not lose anything by uploading.

**Comment by stardevrk** [comment]
@shirlymanor 
I have just removed original video to Windows. It was same as downloaded video.
It was my mistake.
Thank you @shirlymanor
